### PR TITLE
test(e2e): new E2E tests scenarios (#2980)

### LINKED ISSUE #2980: Add New E2E Tests
### Description
It would be useful to add more E2E tests to ensure better code coverage and improve quality control for the kics development.

In addition, adding tests with regex allows the validation of the CLI output, such as validate an UUID output or check if after a successful scan, the output contains all the necessary variables like 'Scan Duration', 'Files scanned',  'Queries loaded'.

### PR DESCRIPTION
**Pull request by cxlucas**
Closes #2980

**Proposed Changes**
- Added E2E tests for better quality control.
- Added validation function that allows regex-based tests for some test cases such as validation of UUID.

| Test Name   | Description                                                                                                                                                                                                                      | Expected Output | Exit Status Code |
|-------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------|------------------|
| E2E-CLI-006 |                                                                               KICS generate-id command should display a valid uuid text in the CLI                                                                               | match regex     | 0                |
| E2E-CLI-007 |                    KICS scan command should display a scan results summary in the CLI when provided with the --path flag and it should contains elements like Queries Loaded: <Number>, Files Scanned: <Number>                   | match regex     | 0                |
| E2E-CLI-008 |                                                                              KICS scan command with silent flag must hide all textual output in CLI                                                                              | stdout          | 0                |
| E2E-CLI-009 |                                                                        KICS scan command with no-progress flag must hide the progress bar output in the CLI                                                                       | match regex     | 0                |
| E2E-CLI-010 | KICS scan command with -t flag must receive a valid type argument  like: 'Kubernetes', 'Dockerfile' to be able to perform the scan. If user given an unknown argument, kics must exhibit an error message and return exit code 1 | match regex     | 1                |
| E2E-CLI-011 |         KICS scan command with -t flag must receive a valid type argument  like: 'Kubernetes', 'Dockerfile' to be able to perform the scan. If user given a valid case insensitive argument, kics must successfully scan         | stdout          | 0                |
| E2E-CLI-012 |                                                       KICS scan command with --minimal-ui flag should perform a scan without showing detailed results on each line of code                                                       | match regex     | 0                |
| E2E-CLI-013 |                                                                        KICS root command list-platforms must return all the supported platforms in the CLI                                                                       | stdout          | 0                |
|             |                                                                                                                                                                                                                                  |                 |                  |

I submit this contribution under Apache-2.0 license.

### CODE REVIEW

**Comment by rogeriopeixotocx** [comment]
@cxlucas It's looking good can you update the `README.md` file with the details about the new validation feature.

**Comment by cxlucas** [comment]
> @cxlucas It's looking good can you update the `README.md` file with the details about the new validation feature.

Thanks for notifying, I will update the readme soon.

**Review by rogeriopeixotocx — CHANGES_REQUESTED** [review]
This LGTM, but I would like @felipe-avelar, @joaoReigota1 and @rubensequeiracx to also review & approve.

**Review by joaoReigota1 — APPROVED** [review]
LGTM

**Review by rogeriopeixotocx — APPROVED** [review]

**Pull request merged**
