### PR TITLE
feat: rewrite passwords and secrets query to use regex based strategy

### LINKED ISSUE #4062: Secrets query too wide and creates False Positives
### Expected Behavior
Should only find the right hard-coded issues
### Actual Behavior
Finds too many FPs

### PR DESCRIPTION
**Pull request by rogeriopeixotocx**
Closes #4062

Related with #3905 #3773

**Proposed Changes**
- Use regex-based approach to search original document and find results
- Enable configuration of regex-based rules
- Enable entropy calculation per matched regex group
- Creates a new `secrets.Inspector` that runs before the `engine.Inspector` during a Service scan

**Refactor**
- Similarity ID has its own go package 
- Vulnerability builder broken into smaller files
- Tests fixes

**TODO**

- [x] More samples covering all regex rules ( @rafaela-soares )
- [x] flag to turn off secrets scanning (`--disable-secrets`)
- [x] Parametrize RegexRules configuration file with flag (`--secrets-regexes-path`)
- [x] Unit tests
- [x] Progress Report
- [x] Performance Profiling @joaoReigota1 
- [x] AllowRules to exclude FP results
- [x] Fix detect line for edge cases (multiple multiline results in the same document) @joaoReigota1 
- [x] Generic AllowRules for all queries @joaoReigota1 
- [x] Documentation update @rafaela-soares 

Implementation inspired by [gitleaks](https://github.com/zricethezav/gitleaks) project

I submit this contribution under the Apache-2.0 license.

### CODE REVIEW

**Review by felipe-avelar — APPROVED** [review]
Awesome work. LGTM.

**Review by joaoReigota1 — DISMISSED** [review]
LATM!

**Comment by joaoReigota1** [comment]
Metrics
```
------------------MASTER -------------------

Measure units: s

Total CPU usage for file_type_analyzer AVG: 2.66
Total CPU usage for get_queries AVG: 50.50
Total CPU usage for start_scan AVG: 630.55

Measure units: MB

Total MEM usage for file_type_analyzer AVG: 4.16
Total MEM usage for get_queries AVG: 524.75
Total MEM usage for start_scan AVG: 886.34

------------------ PASSWORDS & SECRETS PR ----------------

Measure units: s

Total CPU usage for file_type_analyzer AVG: 3.26
Total CPU usage for get_queries AVG: 47.26
Total CPU usage for prepare_sources AVG: 13.73
Total CPU usage for start_scan AVG: 569.68

Measure units: MB

Total MEM usage for file_type_analyzer AVG: 3.84
Total MEM usage for get_queries AVG: 524.67
Total MEM usage for prepare_sources AVG: 1.29
Total MEM usage for start_scan AVG: 886.08
```
* metrics were taken by running all queries against themselves

**Review by joaoReigota1 — APPROVED** [review]
LGTM!

**Comment by JonZeolla** [comment]
@rogeriopeixotocx awesome work!  Looking forward to trying this out.

**Pull request merged**
