### PR TITLE
fix(parser): support nameless tf resources

### PR DESCRIPTION
**Pull request by liorj-orca**
this PR solves the fatal error we are getting when scanning a TF resources without a name. for exmple for the following, we were getting the following fatal error:
```
resource "aws_lb" {
  name               = "test-lb-tf"
  internal           = false
  load_balancer_type = "network"
  subnets            = [for subnet in aws_subnet.public : subnet.id]

  enable_deletion_protection = true

  tags = {
    Environment = "production"
  }
}

resource "aws_lb" {
  name               = "test-lb-tf"
  internal           = false
  load_balancer_type = "network"
  subnets            = [for subnet in aws_subnet.public : subnet.id]

  enable_deletion_protection = true

  tags = {
    Environment = "production"
  }
}
```

the error we are getting:
```
panic: interface conversion: interface {} is []interface {}, not model.Document

goroutine 13 [running]:
github.com/Checkmarx/kics/pkg/parser/terraform.processResources(0x1e43a80?, {0x4000230f40, 0xa})
	/app/pkg/parser/terraform/terraform.go:75 +0x1d8
github.com/Checkmarx/kics/pkg/parser/terraform.addExtraInfo({0x400012e250?, 0x1, 0x1}, {0x4000230f40, 0xa})
	/app/pkg/parser/terraform/terraform.go:93 +0xac
github.com/Checkmarx/kics/pkg/parser/terraform.(*Parser).Parse(0x4000f1d300, {0x4000230f40, 0xa}, {0x4000c426c0, 0x223, 0x240})
	/app/pkg/parser/terraform/terraform.go:133 +0x188
github.com/Checkmarx/kics/pkg/parser.(*Parser).Parse(0x4000f255c0, {0x4000230f40, 0xa}, {0x4000c426c0, 0x223, 0x240})
	/app/pkg/parser/parser.go:128 +0x120
github.com/Checkmarx/kics/pkg/kics.(*Service).sink(0x40005e9730, {0x2765410, 0x400013a000}, {0x4000230f40, 0xa}, {0x210a8c2, 0x7}, {0x2748400, 0x400012e040}, {0x4001200000, ...})
	/app/pkg/kics/sink.go:42 +0x134
github.com/Checkmarx/kics/pkg/kics.(*Service).PrepareSources.func1({0x2765410, 0x400013a000}, {0x4000230f40, 0xa}, {0x2753608?, 0x400012e040})
	/app/pkg/kics/service.go:71 +0xa8
github.com/Checkmarx/kics/pkg/engine/provider.(*FileSystemSourceProvider).GetSources(0x40001284c0, {0x2765410, 0x400013a000}, 0x87354?, 0x40004c0dc0, 0x0?)
	/app/pkg/engine/provider/filesystem.go:129 +0x140
github.com/Checkmarx/kics/pkg/kics.(*Service).PrepareSources(0x40005e9730, {0x2765410, 0x400013a000}, {0x210a8c2, 0x7}, 0x4000cf8120?, 0x4000cf8180?)
	/app/pkg/kics/service.go:67 +0x1c0
created by github.com/Checkmarx/kics/pkg/scanner.PrepareAndScan
	/app/pkg/scanner/scanner.go:24 +0xb4
```

overall, tf resources withtout a name are not valid, but I belive it would be better inspecting those resources anyway and be able to indicate other issues we have on them other than completly fail the scan 

**Proposed Changes**
-
-
-

I submit this contribution under the Apache-2.0 license.

### CODE REVIEW

**Comment by lior-orca** [comment]
@cxMiguelSilva any chance you look on this one?

**Review by cxMiguelSilva — CHANGES_REQUESTED** [review]
Hi @liorj-orca, sorry for the late response,
The proposed changes to the Terraform parser LGTM. Would you just be able to add a unit test to ensure that this issue will be validated from other changes from now onward?

**Comment by liorj-orca** [comment]
Hi @cxMiguelSilva, i added a simple test  for that, can we push it forward?

**Review by cxMiguelSilva — APPROVED** [review]
LGTM

**Comment by cxMiguelSilva** [comment]
> Hi @cxMiguelSilva, i added a simple test for that, can we push it forward? cc: @gabriel-cx @lior-orca @kaplanlior

Hi @liorj-orca, I have made the initial code review, and now it will be submitted to QA analysis. Once we have the ok we will merge it. Thank you so much for this contribution to this missing case on the Terraform parser 😀

**Pull request merged**
