### PR TITLE
update(query): add CWE information to volume_has_sensitive_host_directory

### PR DESCRIPTION
**Pull request by julianthome**
** Reason for Proposed Changes**
- CWE information for the query was missing

** Proposed Changes**
- Adding 668 as Exposure of Resource to Wrong Sphere seems the best fit covering both confidentiality and integrity concerns.

I submit this contribution under the Apache-2.0 license.

### CODE REVIEW

**Review by ArturRibeiro-CX — COMMENTED** [review]
Hi @julianthome, 
Thanks for your the contribution!
At the moment, the query metadata does not have 2 required fields, which is causing the e2e tests to fail, as you can see in the actions pipeline below. 
Can you kindly add _oldSeverity_ and _cloudProvider fields to the metadata, like so: 
`"descriptionID": "8361cc0a",
"oldSeverity": "HIGH",
"cloudProvider": "common",
"cwe": "668"
}`
As soon as you do, I'll approve the PR.

Best regards.

**Comment by julianthome** [comment]
Thanks a lot @ArturRibeiro-CX ... would you mind re-checking the update. Are the changes acceptable?

**Review by ArturRibeiro-CX — APPROVED** [review]
Hi @julianthome, 
Thanks for you contribution, those changes are enough. 
We'll merge this PR as soon as possible. 
Best regards.

**Comment by ArturRibeiro-CX** [comment]
Hi @julianthome, 
Just to let you know that your PR was merged today. 
Thanks for your contribution to KICS. 

Best regards.

**Pull request merged**
