### PR TITLE
feat(query): added "SES Policy With Public Access" for Ansible and Terraform

### PR DESCRIPTION
**Pull request by cosmicgirl97**
**Proposed Changes**
- Added "SES Policy With Public Access" for Ansible and Terraform

🚨 SEVERITY AND CATEGORY NEED REVIEW 🚨

I submit this contribution under the Apache-2.0 license.

### CODE REVIEW

**Review by JoaoDuarteGomes — CHANGES_REQUESTED** [review]
Category and severity look good.
Query name and description should be reviewed to match, "public access" != "allow IAM actions to all principals".

**Review by joaoReigota1 — APPROVED** [review]
LGTM

**Review by JoaoDuarteGomes — DISMISSED** [review]
LGTM.

**Review by joaoReigota1 — APPROVED** [review]
LGTM

**Pull request merged**
