### PR TITLE
feat(query): add new query for tencentcloud CVM resource

### PR DESCRIPTION
**Pull request by SevenEarth**
Hello,  There is something new query for TencentCloud CVM resource:
1. cvm_instance_using_default_vpc
2. cvm_instance_using_default_security_group
3. cvm_instance_has_public_ip
4. cvm_instance_disable_monitor_service

Please help review the PR 
Thanks

I submit this contribution under the Apache-2.0 license.

### CODE REVIEW

**Comment by SevenEarth** [comment]
I submit this contribution under the Apache-2.0 license.

**Comment by gabriel-cx** [comment]
Hi @SevenEarth ,

Thank you very much for this contribution!!
We'd like to request you 2 steps:

- Kindly take a look at the failing tests
image


- Please add a prefix "`(Beta)`" to the queries name, like in [this one](https://github.com/Checkmarx/kics/blob/master/assets/queries/terraform/tencentcloud/disk_encryption_disabled/metadata.json#L3). For now we need this because when all the tests pass we will merge this PR, but the queries will need to be reviewed by our AppSec later one as well. This "`(Beta)`" prefix will help the users to know that this queries are part of KICS but they are still under review.

**Comment by SevenEarth** [comment]
> Hi @SevenEarth ,
> 
> Thank you very much for this contribution!! We'd like to request you 2 steps:
> 
> * Kindly take a look at the failing tests
> 
> image
> * Please add a prefix "`(Beta)`" to the queries name, like in [this one](https://github.com/Checkmarx/kics/blob/master/assets/queries/terraform/tencentcloud/disk_encryption_disabled/metadata.json#L3). For now we need this because when all the tests pass we will merge this PR, but the queries will need to be reviewed by our AppSec later on as well. This "`(Beta)`" prefix will help the users to know that this queries are part of KICS but they are still under review.

Hello, Thank you for your review.
I have a question about the first bug：
I ran the following code locally for testing, and the result was normal without any errors
`go run ./cmd/console/main.go scan -p  "/Users/yanxiang/Tencent/Kics/kics/assets/queries/terraform/tencentcloud/cvm_instance_has_public_ip/test" -d "/Users/yanxiang/Tencent/Kics/kics/assets/queries/terraform/tencentcloud/cvm_instance_has_public_ip/test/input.json"`
image
May I ask where is the detailed log of the failed e2e test? I want to see the reason for the error?

**Comment by SevenEarth** [comment]
ohhh, I guess it's probably a 'module' issue

**Comment by gabriel-cx** [comment]
@SevenEarth , the unit-tests are the ones that are failing. The e2e is failing because another reason, do not worry! :D
Seems like what you expected to happen in your [positive_expected_result.json](https://github.com/Checkmarx/kics/pull/7122/files#diff-013ad70cdac660ad7dca3107cbef65738a8666b0d3b88d90017e7b8ed5109f24) is not happening, for all the 4 new queries added.

**Comment by SevenEarth** [comment]
> @SevenEarth , the unit-tests are the ones that are failing. The e2e is failing because another reason, do not worry! :D Seems like what you expected to happen in your [positive_expected_result.json](https://github.com/Checkmarx/kics/pull/7122/files#diff-013ad70cdac660ad7dca3107cbef65738a8666b0d3b88d90017e7b8ed5109f24) is not happening, for all the 4 new queries added.

Thank you
I fix all problems
There is my local test
Please help review the PR 😁
企业微信截图_058de1f9-eb47-43a0-aba7-6e657d5183db

**Review by gabriel-cx — APPROVED** [review]

**Comment by gabriel-cx** [comment]
@SevenEarth , thank you for this amazing contribution!!

**Pull request merged**
