### PR TITLE
add homebrew install

### LINKED ISSUE #1657: Add choco/brew packages to install KICS binaries
**Describe the solution you'd like**
Existing packages for one command installation of kics binaries on Windows/linux

### PR DESCRIPTION
**Pull request by paulopontesm**
Closes  #1657 (at least the brew part)

**Proposed Changes**
- Add instructions to install kics with homebrew

I submit this contribution under the Apache-2.0 license.

### CODE REVIEW

**Review by nunoocx — CHANGES_REQUESTED** [review]
Thanks for the contribution, @paulopontesm.
Can you please move this section a bit down, after the UBI-based Image?

**Comment by paulopontesm** [comment]
> Thanks for the contribution, @paulopontesm. Can you please move this section a bit down, after the UBI-based Image?

Moved down 👍

**Review by joaoReigota1 — APPROVED** [review]
LGTM

**Review by nunoocx — APPROVED** [review]
LGTM

**Pull request merged**
