### PR TITLE
Add "Invalid Operation External Documentation URL" query for OpenAPI #2887

### LINKED ISSUE #2887: Add "Invalid Operation External Documentation URL" query for OpenAPI
### Platform
OpenAPI

### Description
Operation External Documentation URL should be a valid URL

### PR DESCRIPTION
**Pull request by rafaela-soares**
Signed-off-by: Rafaela Soares rafaela.soares@checkmarx.com

Closes #2887

**Proposed Changes**
- Added "Invalid Operation External Documentation URL" query for OpenAPI (it checks if paths[path][operation].externalDocs.url has an invalid URL)

I submit this contribution under Apache-2.0 license.

### CODE REVIEW

**Review by felipe-avelar — COMMENTED** [review]
What happened with `.github/scripts/is-changed-since-last-nightly.sh`?

**Comment by rogeriopeixotocx** [comment]
Probably some errors during merge... content of the script `.github/scripts/is-changed-since-last-nightly.sh` was removed

**Comment by rogeriopeixotocx** [comment]
Also there's an empty json file called `payload.json` that should not be there.

**Review by rogeriopeixotocx — APPROVED** [review]
LGTM

**Pull request merged**
