### PR TITLE
feat(query): add new query for tencentcloud CVM resource

### PR DESCRIPTION
**Pull request by SevenEarth**
Hello, There is something new query for TencentCloud TKE resource:

cvm_instance_using_user_data

Please help review the PR
Thanks

I submit this contribution under the Apache-2.0 license.

### CODE REVIEW

**Comment by SevenEarth** [comment]
This is my local test
image

**Comment by SevenEarth** [comment]
Hello
Please help review the PR
Thanks

**Review by ArturRibeiro-CX — CHANGES_REQUESTED** [review]
Looks good to me but could we also add positive expected results for "secretId" and "secretKey" since the regex is also looking for those values? 
Thanks for your contribution!

**Review by ArturRibeiro-CX — APPROVED** [review]

**Comment by SevenEarth** [comment]
> Looks good to me but could we also add positive expected results for "secretId" and "secretKey" since the regex is also looking for those values? Thanks for your contribution!

Yes, you are right. I will improve it

**Pull request merged**
