### PR TITLE
feat(query): Added query Additional Properties Too Permissive for open api

### PR DESCRIPTION
**Pull request by felipe-avelar**
Signed-off-by: Felipe Avelar <felipe.avelar@checkmarx.com>

**Proposed Changes**
- Added query Additional Properties Too Permissive for open api

I submit this contribution under the Apache-2.0 license.

### CODE REVIEW

**Review by joaoReigota1 — CHANGES_REQUESTED** [review]
I think that we should add a rule that checks when it is `allOf` that `additionalProperties` is not set to false

**Comment by felipe-avelar** [comment]
> I think that we should add a rule that checks when it is `allOf` that `additionalProperties` is not set to false

This will be resolved by another query

**Review by joaoReigota1 — APPROVED** [review]
LGTM

**Review by rogeriopeixotocx — APPROVED** [review]
LGTM

**Pull request merged**
