### PR TITLE
Bugs/kics/mask secrets

### PR DESCRIPTION
**Pull request by roy-yablonka**
Closes https://github.com/Checkmarx/kics/issues/6264
running mask regexes for secrets on kics' results regardless of whether flag "--disable-secrets" was raised

### CODE REVIEW

**Comment by lior-orca** [comment]
@roy-yablonka i think it will be best to add a new flag to control of to show the secrets or not...

**Comment by lior-orca** [comment]
@roy-yablonka UP on my latest comment

**Comment by roy-yablonka** [comment]
> @roy-yablonka UP on my latest comment

Hi, yes I understand that an additional change for this feature will have this code run only once **--disable-secrets** flag is on.

**Comment by lior-orca** [comment]
@roy-yablonka I meant that it will be ideal to have one more flag, e.g. "mask-secrets", in order to decide if to show/hide the secrets.

**Comment by cxMiguelSilva** [comment]
changes moved to #6349

**Pull request closed without merging**
