### PR TITLE
feat(query): added "Redshift Using Default Port" for Ansible, CloudFormation, and Terraform

### PR DESCRIPTION
**Pull request by cosmicgirl97**
**Proposed Changes**
- Added "Redshift Using Default Port" for Ansible, CloudFormation, and Terraform

🚨 SEVERITY AND CATEGORY NEED REVIEW 🚨

I submit this contribution under the Apache-2.0 license.

### CODE REVIEW

**Review by joaoReigota1 — APPROVED** [review]
LGTM

**Review by rjegoncalves — CHANGES_REQUESTED** [review]
Categories OK.
Severities should be Low.

**Review by rjegoncalves — DISMISSED** [review]
LGTM

**Review by joaoReigota1 — APPROVED** [review]
LGTM

**Pull request merged**
