### PR TITLE
feat(query): added "RDS Using Default Port" for Ansible, CloudFormation, and Terraform

### PR DESCRIPTION
**Pull request by cosmicgirl97**
**Proposed Changes**
- Added "RDS Using Default Port" for Ansible, CloudFormation, and Terraform

🚨 SEVERITY AND CATEGORY NEED REVIEW 🚨

I submit this contribution under the Apache-2.0 license.

### CODE REVIEW

**Review by joaoReigota1 — DISMISSED** [review]
LGTM

**Review by JoaoDuarteGomes — CHANGES_REQUESTED** [review]
Category looks good.
Severity should be LOW.

**Review by JoaoDuarteGomes — DISMISSED** [review]
LGTM.

**Review by felipe-avelar — APPROVED** [review]
LGTM

**Pull request merged**
