### PR TITLE
feat(query): added "Google Compute Network Using Firewall Rule that Allows All Ports" for Ansible and Terraform

### PR DESCRIPTION
**Pull request by cosmicgirl97**
**Proposed Changes**
- Added "Google Compute Network Using Firewall Rule that Allows All Ports" for Ansible and Terraform

🚨 SEVERITY AND CATEGORY NEED REVIEW 🚨

I submit this contribution under the Apache-2.0 license.

### CODE REVIEW

**Comment by joaoReigota1** [comment]
Is this PR duplicated of https://github.com/Checkmarx/kics/pull/4511?

**Comment by cosmicgirl97** [comment]
> Is this PR duplicated of #4511?

No. #4511 verifies if any port matches the regex `[0-9]+-[0-9]+` (port range) but excludes the case of 0-65535 (all ports)

**Review by joaoReigota1 — APPROVED** [review]
LGTM

**Review by JoaoDuarteGomes — APPROVED** [review]
LGTM.

**Pull request merged**
