### PR TITLE
feat(query): add "SNS Topic Encrypted With AWS Managed Key" for Terraform

### PR DESCRIPTION
**Pull request by rafaela-soares**
Signed-off-by: Rafaela Soares rafaela.soares@checkmarx.com

**Proposed Changes**
- Added "SNS Topic Encrypted With AWS Managed Key" query for Terraform. It checks if the SNS Topic is encrypted with AWS managed key (`alias/aws/sns`)

I submit this contribution under the Apache-2.0 license.

### CODE REVIEW

**Review by rogeriopeixotocx — APPROVED** [review]
LGTM

**Comment by aminvielledebatAtBedrock** [comment]
Hi @rafaela-soares !

We (with @jycamier :heart:) are hurting with this rule, and several others about encryption, in our scans because we used to use aws kms managed key.

Could you explain us why this rule is implemented, and why it's tagged as `HIGH` please ?

**Comment by rafaela-soares** [comment]
Hello @aminvielledebatAtBedrock!

Glad to see you here! Thank you so much for using KICS and reaching us.
My regards to @jycamier!

From my understanding, KMS Customer Master Keys (CMKs) should be used instead of AWS Managed Keys, because when using AWS Managed Keys, the default keys will be used since there are no Customer Managed Keys (which do not provide sufficient control over encryption and decryption). KMS Customer Master Keys (CMKs) provide more control since you can see the key policy, for example.

In order to give you a more detailed explanation, I will ask our AppSec team to join this thread. Additionally to that, I will request description improvement for this kind of query.

Hope to continue to see you all around😊

**Comment by rjegoncalves** [comment]
Hi @aminvielledebatAtBedrock!

Rafaela's explanation is very much on point. Another relevant note here is that using Customer Managed Keys (CMKs) will provide full control to the customer over the encrypted data - which is needed to meet some regulatory compliance requirements.

**Comment by jycamier** [comment]
Hi @rafaela-soares and @rjegoncalves,

Thanks for your answers !

Indeed ! We find more information about it. Maybe we're concerned.
It's a PEBKAC ! Sorry for the noise !

**Pull request merged**
