### PR TITLE
fix(query): terraform/aws/iam_access_key_is_exposed

### LINKED ISSUE #5845: the query terraform/aws/iam_access_key_is_exposed seems to be wrong
Refering to [AWS documentation "Ensure no root user access key exists"](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-cis-controls.html#securityhub-cis-controls-1.12), I think the query `queries/terraform/aws/iam_access_key_is_exposed` is wrong.

However, the cloudFormation query version `assets/queries/cloudFormation/root_account_has_active_access_keys` seems legit.

### Expected Behavior

```rego
package Cx

CxPolicy[result] {
	access_key := input.document[i].resource.aws_iam_access_key[name]

	lower(object.get(access_key, "status", "Active")) == "active"

	access_key.user == "root"

	result := {
		"documentId": input.document[i].id,
		"searchKey": sprintf("aws_iam_access_key[%s].user", [name]),
		"issueType": "IncorrectValue",
		"keyExpectedValue": sprintf("'aws_iam_access_key[%s].user' must not set to 'root' for an active access key", [name]),
		"keyActualValue": sprintf("'aws_iam_access_key[%s].user' is root for an active access key", [name]),
	}
}
```

### Actual Behavior

```rego
package Cx

CxPolicy[result] {
	access_key := input.document[i].resource.aws_iam_access_key[name]

	lower(object.get(access_key, "status", "Active")) == "active"

	access_key.user != "root"

	result := {
		"documentId": input.document[i].id,
		"searchKey": sprintf("aws_iam_access_key[%s].user", [name]),
		"issueType": "IncorrectValue",
		"keyExpectedValue": sprintf("'aws_iam_access_key[%s].user' is 'root' for an active access key", [name]),
		"keyActualValue": sprintf("'aws_iam_access_key[%s].user' is '%s' for an active access key", [name, access_key.user]),
	}
}
```

### PR DESCRIPTION
**Pull request by jycamier**
Closes #5845

Referring to [AWS CIS Controls 1.12](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-cis-controls.html#securityhub-cis-controls-1.12)

**Proposed Changes**
- fix the query
- fix the tests

I submit this contribution under the Apache-2.0 license.

### CODE REVIEW

**Review by cxMiguelSilva — CHANGES_REQUESTED** [review]
Hi @jycamier, thank you so much for your contribution!!
Regarding the changes to the Security Query, I think that indeed the approach is incorrect and your approach fixes it to the correct behavior. 
I would like just to request some changes.
- Change the `keyExpectedValue` keyword  from `must` to `should` in order to align the approach recently taken for all the new/changed Security Queries
- Change the query matadata.json `descriptionText` to `IAM Access Key should not be active for root users`
- If You feel comfortable updating the Ansible Security Query `IAM Access Key Is Exposed` to be aligned with the  Terraform approach

**Comment by jycamier** [comment]
Hi @cxMiguelSilva

> Change the keyExpectedValue keyword from must to should in order to align the approach recently taken for all the new/changed Security Queries

Done

> Change the query matadata.json descriptionText to IAM Access Key should not be active for root users

Done

> If You feel comfortable updating the Ansible Security Query IAM Access Key Is Exposed to be aligned with the Terraform approach

The rego, without any trouble.
The Ansible tests, not at all.

**Review by cxMiguelSilva — APPROVED** [review]
@jycamier thank you so much for your contribution.
Regarding the Ansible Security Query do not worry about it, we will address it.
The changes LGTM

**Review by rafaela-soares — APPROVED** [review]
LGTM 🚀 

Thank you so much, @jycamier!

**Pull request merged**
