### PR TITLE
update(query): add cwe infos to dockerCompose queries

### LINKED ISSUE #7006: feat(cwe): add CWE information to docker-compose queries
**Is your feature request related to a problem? Please describe.**
KICS does not deliver CWE information for all detected flaws. Currently it is added only to dockerfile and common queries.

**Describe the solution you'd like**
Add the best matching CWE ID to the metadata.json of the queries.

### PR DESCRIPTION
**Pull request by ArturRibeiro-CX**
Closes #7006

**Reason for Proposed Changes**
- dockerCompose queries don't provide cwe infos;

**Proposed Changes**
- add cwe infos to all dockerCompose queries;
- add cloudProvider common to all queries;
- add oldSeverity to queries metadata;
- update e2e with cloudProvider and cwe field;
- fix typo on query description;
- fix negative2 and positive3 test samples since they were wrongly constructed; 

I submit this contribution under the Apache-2.0 license.

### CODE REVIEW

**Review by cx-ruiaraujo — APPROVED** [review]
LGTM!
For all pipelines to pass, [PR-7153](https://github.com/Checkmarx/kics/pull/7153) needs to be merged first.

**Review by JulioSCX — DISMISSED** [review]
LGTM, great job adding the CWEs to all queries as well as fixing other smaller issues you found along the way!

**Review by EduardoSemanas — APPROVED** [review]
LGTM

**Review by EduardoSemanas — APPROVED** [review]
LGTM

**Pull request merged**
