### PR TITLE
Update key_vault_soft_delete_enabled query Closes #2056

### LINKED ISSUE #2056: Update key_vault_soft_delete_enabled query for Terraform
**Platform**
Terraform

**Provider**
Azure

**Description**
This query has become useless according to the latest Terraform Documentation.

### PR DESCRIPTION
**Pull request by NunoAraujoCX**
Closes #2056 

**Proposed Changes**

- Clean an unnecessary query according to the new Terraform Documentation
- Source: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault

I submit this contribution under Apache-2.0 license.

### CODE REVIEW

**Comment by joaomartinscx** [comment]
@NunoAraujoCX Can you add a link to the docs you mention that make this query unnecessary?

**Comment by NunoAraujoCX** [comment]
@joaomartinscx Added link to the docs

**Review by joaomartinscx — APPROVED** [review]
Everything looks good to me, good job!

**Review by felipe-avelar — APPROVED** [review]
LGTM

**Pull request merged**
