### PR TITLE
Update integrations.md

### PR DESCRIPTION
**Pull request by markmishaevcx**

### CODE REVIEW

**Comment by markmishaevcx** [comment]
Scan submitted to Checkmarx

**Comment by markmishaevcx** [comment]
Scan not submitted to Checkmarx due to existing Active scan for the same project.

**Comment by markmishaevcx** [comment]
Logo<br />**Checkmarx SAST - Scan Summary & Details**
### Cx-SAST Summary
Total of 4 vulnerabilities<br />High&nbsp;**0 High**<br />Medium&nbsp;**3 Medium**<br />Low&nbsp;**1 Low**<br />Info&nbsp;**0 Info**<br />
### Violation Summary
Medium&nbsp;**3** **Medium**<br />
[View more details on Checkmarx UI](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1049094&projectid=738)
### Cx-SAST Details
|Lines|Severity|Category|File|Link|
---|---|---|---|---
[30](https://github.com/Checkmarx/kics/blob/kics-integration-documentation/cmd/builder/main.go#L30) |Medium|Path_Traversal|cmd/builder/main.go|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1049094&projectid=738&pathid=3)
[83](https://github.com/Checkmarx/kics/blob/kics-integration-documentation/test/main_test.go#L83) |Medium|Denial_Of_Service_Resource_Exhaustion|test/main_test.go|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1049094&projectid=738&pathid=2)
[52](https://github.com/Checkmarx/kics/blob/kics-integration-documentation/pkg/kics/service.go#L52) |Medium|Denial_Of_Service_Resource_Exhaustion|pkg/kics/service.go|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1049094&projectid=738&pathid=1)

**Review by elit-cx — APPROVED** [review]

**Review by IgorMarkov — COMMENTED** [review]
change:
infrastructure-as-a-code (IaC)

to
infrastructure as code (IaC)

**Pull request merged**
