### PR TITLE
fix: spelling mistake in scan.go 

### PR DESCRIPTION
**Pull request by Homopatrol**
**Proposed Changes**
`			"accetps" -> "accepts"
`

I submit this contribution under the Apache-2.0 license.

### CODE REVIEW

**Review by rogeriopeixotocx — DISMISSED** [review]

**Comment by rogeriopeixotocx** [comment]
Hi @Homopatrol can you also fix this typo in the following files?
https://github.com/Checkmarx/kics/blob/master/e2e/fixtures/assets/scan_help#L23
https://github.com/Checkmarx/kics/blob/master/docs/commands.md

**Comment by Homopatrol** [comment]
@rogeriopeixotocx okay i've updated those files as well 👍🏽

**Comment by rogeriopeixotocx** [comment]
Hi @Homopatrol could you please rebase your branch to the current master branch? 
I'm really sorry for the inconvenience.
The PR checks should be passing after this.

**Review by rogeriopeixotocx — APPROVED** [review]
LGTM, thanks for the contribution @Homopatrol

**Pull request merged**
