### PR TITLE
fix(workflow): fix Pwn Request Vulnerability

### PR DESCRIPTION
**Pull request by AdnaneKhan**
**Proposed Changes**
- Update the validate PR workflow to prevent injection vulnerability

It should be a quick fix for you.

**Reference:**
https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

I submit this contribution under the Apache-2.0 license.

### CODE REVIEW

**Comment by AdnaneKhan** [comment]
Fixed title injection for y'all too :)

**Review by kaplanlior — APPROVED** [review]
LGTM

@freitasmillena - FYI

**Review by nunoocx — APPROVED** [review]
LGTM

**Comment by freitasmillena** [comment]
Thank you so much for contributing! I will carefully read the referenced article :)

**Pull request merged**
