### PR TITLE
delete(query): Remove false positive host_aliases_undefined_or_empty k8s rule

### PR DESCRIPTION
**Pull request by Churro**
**Proposed Changes**

- Remove the rule entirely as, to best of my knowledge, the high severity warning is a false positive:
  - According to [official docs](https://kubernetes.io/docs/tasks/network/customize-hosts-file-for-pods/#why-does-kubelet-manage-the-hosts-file), the kubelet manages the hosts file. Regular DNS resolution _can_ be overridden using `hostAliases` if no resolver is available. This is no security issue though.
  - The rule description mentions that containers should not be able to modify the hosts file after they are started. However, specifying `hostAliases` would not prevent this (as long as `readOnlyRootFilesystem: false`).
  - Requiring a `hostAliases` definition seems flawed in the first place: usually, you **want** to use kube-dns and not list combinations of hostname and IP address manually. This is analogous to how we use the Internet generally, nowadays.

I submit this contribution under the Apache-2.0 license.

### CODE REVIEW

**Comment by rafaela-soares** [comment]
Hello, @Churro! 

Your PR has not been forgotten. Thank you so much for being so collaborative 😊

**Comment by rafaela-soares** [comment]
Hello again, @Churro!

Our security team confirmed that you are right! Thank you so much for noticing and reporting! 🚀 

We will be glad to add your contribution to the next release (it will be launched tomorrow). Can we ask you to also delete the query `kics/assets/queries/terraform/kubernetes/host_aliases_undefined_or_empty`, please?

**Comment by Churro** [comment]
Hi @rafaela-soares,

Thank you for following up on this! As requested, I've now also deleted the TF rule.

**Comment by rafaela-soares** [comment]
Hello again, @Churro!

Sorry for bothering again. Can you please merge the branch with the KICS master? We had a bug in the validate-queries-metadata test.

**Comment by Churro** [comment]
Sure, no problem. Seems to work fine now 👍

**Review by rafaela-soares — APPROVED** [review]
Thank you much, @Churro! 🚀

**Pull request merged**
